# Generated by Django 5.0.6 on 2025-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('service', models.CharField(max_length=100)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
            ],
        ),
    ]
