# Generated by Django 5.1.7 on 2025-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.CharField(choices=[('CICS201', 'CICS 201'), ('CICS202', 'CICS 202'), ('CPE_FACULTY', 'CpE FACULTY'), ('COMP_LAB_CICS', 'COMPUTER ENGINEERING LAB (CICS)'), ('COMP_LAB_EINSTEIN', 'COMPUTER LAB (EINSTEIN BUILDING)'), ('ICT_FACULTY', 'ICT FACULTY (GYM)')], default='CICS201', max_length=50),
        ),
    ]
