# Generated by Django 5.1.7 on 2025-03-17 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentWebsite', '0003_studentfile_appointment_student_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_private', models.BooleanField(default=False, help_text='If checked, only faculty can see this comment')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to=settings.AUTH_USER_MODEL)),
                ('student_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AppointmentWebsite.studentfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
