# Generated by Django 5.2 on 2025-04-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentWebsite', '0002_timeslot'),
        ('AppointmentWebsite', '0005_alter_appointment_status'),
    ]

    operations = [
    ]
