# Generated by Django 5.2 on 2025-04-06 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentWebsite', '0006_merge_0002_timeslot_0005_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.CharField(choices=[('CICS201', 'CICS 201'), ('CICS202', 'CICS 202'), ('CPE_FACULTY', 'CpE FACULTY'), ('COMP_LAB_CICS', 'COMPUTER ENGINEERING LAB (CICS)'), ('COMP_LAB_EINSTEIN', 'COMPUTER LAB (EINSTEIN BUILDING)'), ('ICT_FACULTY', 'ICT FACULTY (GYM)')], default='CICS201', max_length=50),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
