# Generated by Django 5.0.2 on 2025-04-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentWebsite', '0009_userprofile_department_userprofile_office_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('thesis', 'Thesis Defense'), ('proposal', 'Proposal Defense'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
